# countries through which tor traffic will not exit
ExcludeExitNodes {us},{au},{ca},{nz},{gb}                                                  # 5 eyes countries
#ExcludeExitNodes {us},{au},{ca},{nz},{gb},{fr},{dk},{nl},{no}                              # 9 eyes countries
#ExcludeExitNodes {us},{au},{ca},{nz},{gb},{fr},{dk},{nl},{no},{de},{be},{it},{se},{es}     # 14 eyes countries
