---

- name: reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
