---

- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
