---

virtualization_docker_repo_file_url: https://download.docker.com/linux/fedora/docker-ce.repo
virtualization_docker_rpm_key_url: https://download.docker.com/linux/fedora/gpg
virtualization_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

virtualization_virtualbox_repo_file_url: https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
virtualization_virtualbox_rpm_key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
virtualization_virtualbox_extension_pack: https://download.virtualbox.org/virtualbox/7.1.0/Oracle_VirtualBox_Extension_Pack-7.1.0.vbox-extpack  # must match the virtualbox version getting installed
virtualization_virtualbox_packages:
  - VirtualBox-7.1
  - virtualbox-guest-additions