---

vscode_rpm_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
vscode_yum_repository_url: "https://packages.microsoft.com/yumrepos/vscode"
vscode_package_name: code

vscode_extensions:
  - aaron-bond.better-comments
  - formulahendry.code-runner
  - donjayamanne.githistory
  - eamodio.gitlens
  - golang.Go
  - vincaslt.highlight-matching-tag
  - oderwat.indent-rainbow
  - yzhang.markdown-all-in-one
  - ms-python.python
  - ms-python.vscode-pylance
  - humao.rest-client
  - Gruntfuggly.todo-tree
  - shardulm94.trailing-spaces
  - vscodevim.vim
  - visualstudioexptteam.vscodeintellicode
  - ms-azuretools.vscode-docker
  - vscode-icons-team.vscode-icons
  - esbenp.prettier-vscode
  - redhat.vscode-yaml
  - danielroedl.meld-diff
  - davidanson.vscode-markdownlint
  - hashicorp.terraform

...
