---

- name: install zsh and other related packages
  ansible.builtin.dnf:
    name: "{{ zsh_packages }}"
    state: present

- name: change user's shell to zsh
  ansible.builtin.user:
    name: "{{ local_username }}"
    shell: /bin/zsh

- block:
    - name: clone antigen git repo
      ansible.builtin.git:
        repo: "{{ zsh_antigen_git_repo }}"
        dest: "~{{ local_username }}/.antigen"
        version: v2.2.3

    - name: check if .zshrc exists in user's home dir
      ansible.builtin.stat:
        path: "~{{ local_username }}/.zshrc"
      register: dotzshrc

    - name: backup .zshrc if it exists
      ansible.builtin.copy:
        src: "~{{ local_username }}/.zshrc"
        dest: "~{{ local_username }}/.zshrc.orig"
        mode: '0644'
      when: dotzshrc.stat.exists

    - name: copy the sample .zshrc file
      ansible.builtin.copy:
        src: .zshrc
        dest: "~{{ local_username }}/.zshrc"
        mode: '0644'
        force: yes

    - name: copy the sample .shell_*.sh files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "~{{ local_username }}/{{ item }}"
        mode: '0644'
      with_items:
        - .shell_aliases.sh
        - .shell_functions.sh
        - .shell_variables.sh
  become: true
  become_user: "{{ local_username }}"

...
