---

- name: Remove redundant packages often starting unnecessary services
  ansible.builtin.dnf:
    name: "{{ harden_system_redundant_packages }}"
    state: absent

- name: Turn off Link-Local Multicast Name Resolution (LLMNR)
  block:
    - name: Create directory /etc/systemd/resolved.conf.d
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory

    - name: Create custom options file
      ansible.builtin.copy:
        owner: root
        group: root
        mode: '0644'
        dest: /etc/systemd/resolved.conf.d/options.conf
        content: |
          [Resolve]
          LLMNR=no
      notify:
        - Restart systemd-resolved
      changed_when: true

- name: Create new Firewalld zone with hardened rules
  block:
    - name: Create a new firewalld zone called 'FedoraWsHardened'
      ansible.posix.firewalld:
        zone: FedoraWsHardened
        state: present
        permanent: yes

    - name: Set the target of 'FedoraWsHardened' zone to DROP
      ansible.posix.firewalld:
        zone: FedoraWsHardened
        target: DROP
        state: present
        permanent: yes

    - name: Set 'FedoraWsHardened' zone as the default zone
      ansible.builtin.command: firewall-cmd --set-default-zone=FedoraWsHardened
      notify: reload firewalld
