---

- name: fetch hashicorp repo file
  ansible.builtin.get_url:
    url: "{{ hashicorp_repo_file_url }}"
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: '0644'


- name: install hashicorp packages
  ansible.builtin.dnf:
    name: "{{ hashicorp_packages }}"

...
