---

- block:
  - name: add docker rpm key
    ansible.builtin.rpm_key:
      key: "{{ virtualization_docker_rpm_key_url }}"

  - name: fetch docer repo file
    ansible.builtin.get_url:
      url: "{{ virtualization_docker_repo_file_url }}"
      dest: /etc/yum.repos.d/docker.repo
      mode: '0644'

  - name: install docker packages
    ansible.builtin.dnf:
      name: "{{ virtualization_docker_packages }}"

  - name: enable docker service on boot
    ansible.builtin.systemd:
      name: docker.service
      state: started
      enabled: yes

  - name: add user to docker group
    ansible.builtin.user:
      name: "{{ local_username }}"
      append: true
      groups:
        - docker

- block:
  - name: add virtualbox rpm key
    ansible.builtin.rpm_key:
      key: "{{ virtualization_virtualbox_rpm_key_url }}"

  - name: fetch virtualbox repo file
    ansible.builtin.get_url:
      url: "{{ virtualization_virtualbox_repo_file_url }}"
      dest: /etc/yum.repos.d/virtualbox.repo
      mode: '0644'

  - name: install virtualbox packages
    ansible.builtin.dnf:
      name: "{{ virtualization_virtualbox_packages }}"

  - name: enable virtualbox service on boot
    ansible.builtin.systemd:
      name: vboxservice.service
      state: started
      enabled: yes

  - name: add user to vboxuserss group
    ansible.builtin.user:
      name: "{{ local_username }}"
      append: true
      groups:
        - vboxusers
