---

- block:
  - name: add docker rpm key
    ansible.builtin.rpm_key:
      key: "{{ virtualization_docker_rpm_key_url }}"

  - name: fetch docer repo file
    ansible.builtin.get_url:
      url: "{{ virtualization_docker_repo_file_url }}"
      dest: /etc/yum.repos.d/docker.repo
      mode: '0644'

  - name: install docker packages
    ansible.builtin.dnf:
      name: "{{ virtualization_docker_packages }}"

  - name: enable docker service on boot
    ansible.builtin.systemd:
      name: docker.service
      state: started
      enabled: yes

  - name: add user to docker group
    ansible.builtin.user:
      name: "{{ local_username }}"
      append: true
      groups:
        - docker

- block:
  # TODO: revise this task once Fedora official repo releases virtualbox-guest-additions-7.1
  - name: Remove conflicting packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: absent
    with_items: "{{ virtualization_virtualbox_conflict_packages }}"

  - name: add virtualbox rpm key
    ansible.builtin.rpm_key:
      key: "{{ virtualization_virtualbox_rpm_key_url }}"

  - name: fetch virtualbox repo file
    ansible.builtin.get_url:
      url: "{{ virtualization_virtualbox_repo_file_url }}"
      dest: /etc/yum.repos.d/virtualbox.repo
      mode: '0644'

  - name: install virtualbox packages
    ansible.builtin.dnf:
      name: "{{ virtualization_virtualbox_packages }}"

  - name: Download virtualbox extension pack
    ansible.builtin.get_url:
        url: "{{ virtualization_virtualbox_extension_pack.remote_url }}"
        dest: "{{ virtualization_virtualbox_extension_pack.local_path }}"

  - name: Install Virtualbox Extension Pack
    ansible.builtin.command: bash -c "yes y | VBoxManage extpack install --replace {{ virtualization_virtualbox_extension_pack.local_path }}"

  - name: add user to vboxuserss group
    ansible.builtin.user:
      name: "{{ local_username }}"
      append: true
      groups:
        - vboxusers
