import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.9
blur = true

[window.padding]
x = 10
y = 10

[font]
size = 10

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

# uncomment below to start tmux on initial alacritty launch
#[shell]
#program = "/usr/bin/zsh"
#args = ["-c", "if ! tmux ls 2>/dev/null | grep -q -E '^main.*attached'; then tmux attach -t main || tmux new -s main; else /usr/bin/zsh; fi"]
