---

- block:

  - name: Ensure firewalld service is running and enabled on boot
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: true

  - name: Enable firewall
    ansible.posix.firewalld:
      state: enabled
      permanent: true

# It may be desirable to set this to zero, so that application memory is retained as long as possible at the expense
# of the page cache. When there is still a memory shortage, the kernel can still use swapping.
- name: Tune system swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: Update all installed packages to latest
  ansible.builtin.dnf:
    update_only: true
    state: latest

- name: Add RPM Fusion Free repository
  block:
    - name: Import RPM Fusion GPG key from local path
      ansible.builtin.rpm_key:
        key: "{{ base_rpmfusion_free_gpg_key_path }}"
        state: present

    - name: Install RPM Fusion Free release package
      ansible.builtin.dnf:
        name: "{{ base_rpmfusion_free_repo_rpm_url }}"
        state: present

- name: Install archiving tools
  ansible.builtin.dnf:
    name: "{{ base_archiving_tools }}"
    state: present

- name: Install productivity tools
  ansible.builtin.dnf:
    name: "{{ base_productivity_tools }}"
    state: present

- name: Install system tools
  ansible.builtin.dnf:
    name: "{{ base_system_tools }}"
    state: present

- name: Install system tools for laptop
  ansible.builtin.dnf:
    name: "{{ base_system_tools_laptop }}"
    state: present
  when: laptop_mode

- name: Install developer tools
  ansible.builtin.dnf:
    name: "{{ base_developer_tools }}"
    state: present

- name: Install developer tools pipx packages
  community.general.pipx:
    name: "{{ item }}"
  with_items: "{{ base_developer_tools_pipx }}"
  become: true
  become_user: "{{ local_username }}"

- name: Create .ssh dir
  ansible.builtin.file:
    path: "~{{ local_username }}/.ssh"
    state: directory
    mode: '0700'
  become: true
  become_user: "{{ local_username }}"

- block:
    - name: Create directories for golang
      ansible.builtin.file:
        path: "~{{ local_username }}/{{ item }}"
        state: directory
      with_items:
        - go
        - go/src
        - go/bin

    - name: Make GOPATH available in .bashrc
      ansible.builtin.lineinfile:
        path: "~{{ local_username }}/.bashrc"
        line: "{{ item }}"
        create: true
      with_items:
        - export GOPATH=$HOME/go
        - export PATH=$PATH:$GOPATH/bin
  become: true
  become_user: "{{ local_username }}"

- name: Install download tools
  ansible.builtin.dnf:
    name: "{{ base_download_tools }}"
    state: present

- name: Install media packages
  ansible.builtin.dnf:
    name: "{{ base_media_tools }}"
    state: present

- name: Enable permanent night light settings
  ansible.builtin.command: "gsettings set org.gnome.settings-daemon.plugins.color {{ item.key }} {{ item.value }}"
  loop:
    - { key: 'night-light-enabled', value: "{{ base_permanent_night_light.night_light_enabled | string | lower }}" }
    - { key: 'night-light-schedule-automatic', value: "{{ base_permanent_night_light.night_light_schedule_automatic | string | lower }}" }
    - { key: 'night-light-schedule-from', value: "{{ base_permanent_night_light.night_light_schedule_from }}" }
    - { key: 'night-light-schedule-to', value: "{{ base_permanent_night_light.night_light_schedule_to }}" }
    - { key: 'night-light-temperature', value: "{{ base_permanent_night_light.night_light_temperature }}" }

  when: base_permanent_night_light.night_light_enabled
  become: true
  become_user: "{{ local_username }}"

# make fstrim run daily rather than the default weekly schedule for SSD longevity
- block:
    - name: Enable fstrim.timer
      ansible.builtin.systemd:
        name: fstrim.timer
        state: started
        enabled: true

    - name: Create systemd fstrim.timer override dir
      ansible.builtin.file:
        path: /etc/systemd/system/fstrim.timer.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create override.conf file for fstrim.timer
      ansible.builtin.copy:
        src: etc/systemd/system/fstrim.timer.d/override.conf
        dest: /etc/systemd/system/fstrim.timer.d/override.conf
        owner: root
        group: root
        mode: '0644'

    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true

- name: Make poetry create virtualenv dirs inside the project dir itself
  ansible.builtin.command: "poetry config virtualenvs.in-project true"
  become: true
  become_user: "{{ local_username }}"

- name: Build and install golang binaries
  ansible.builtin.command: "go install {{ item }}"
  with_items: "{{ base_golang_tools }}"
  become: true
  become_user: "{{ local_username }}"

- name: Build and install cargo packages
  community.general.cargo:
    name: "{{ item }}"
    locked: "{{ item != 'xh' }}"  # FIXME: workaround for xh installation
    state: latest
  with_items: "{{ base_cargo_packages }}"
  become: true
  become_user: "{{ local_username }}"

- block:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: "{{ base_flatpakrepo_url }}"

    - name: Install flatpak apps from flathub
      community.general.flatpak:
        name: "{{ base_flatpak_flathub_apps }}"
        state: present

- name: Make vim the default editor instead of nano
  ansible.builtin.copy:
    dest: /etc/profile.d/vim.sh
    content: |
      # Set vim as the default editor
      export EDITOR=/usr/bin/vim
      export VISUAL=/usr/bin/vim
    mode: '0644'

...
