---

- name: install vim dnf packages
  ansible.builtin.dnf:
    name: "{{ vim_dnf_packages }}"
    state: present

# TODO: this seems to be not working
- name: Set default text editor to vim
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim
    link: /etc/alternatives/editor

- block:
    - name: clone amix vimrc git repo
      ansible.builtin.git:
        repo: "{{ vim_amix_vimrc_url }}"
        dest: "~{{ local_username }}/.vim_runtime"
        depth: 1

    - name: install amix vimrc
      ansible.builtin.shell: "sh ~/.vim_runtime/install_awesome_vimrc.sh"

    - name: Install indentLine plugin
      ansible.builtin.git:
        repo: "{{ vim_indentline_plugin_url }}"
        dest: "~{{ local_username }}/.vim_runtime/my_plugins/indentLine"

  become: true
  become_user: "{{ local_username }}"

- block:
    - name: create vim undo directory
      ansible.builtin.file:
        path: "~{{ local_username }}/.vim/undodir"
        state: directory
        mode: '0775'

    - name: add custom vim config
      ansible.builtin.copy:
        src: my_configs.vim
        dest: "~{{ local_username }}/.vim_runtime/my_configs.vim"
        mode: '0644'
        force: yes
        backup: yes

  become: true
  become_user: "{{ local_username }}"

...
