---

- name: Install neovim packages
  ansible.builtin.dnf:
    name: "{{ neovim_dnf_packages }}"
    state: present


- block:
    - name: Clone lazyvim starter git repo
      ansible.builtin.git:
        repo: "{{ neovim_lazyvim_starter_url }}"
        dest: "~{{ local_username }}/.config/nvim"
  become: true
  become_user: "{{ local_username }}"

...
